// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1LQcdUl6NLwwZ3G7Fi9Fl1LjSLb9rgvU',
    appId: '1:816750229018:web:f953076759eb300eebc3a3',
    messagingSenderId: '816750229018',
    projectId: 'notify-b02c5',
    authDomain: 'notify-b02c5.firebaseapp.com',
    storageBucket: 'notify-b02c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcQ9vyXGEVNT5OYOIozih2slaYT2fc3K4',
    appId: '1:816750229018:android:d4ce5fbceecfffc0ebc3a3',
    messagingSenderId: '816750229018',
    projectId: 'notify-b02c5',
    storageBucket: 'notify-b02c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrJsnE_XJRHnMq3ay-aOdKartD679tCDs',
    appId: '1:816750229018:ios:f4fe470e1a9bde24ebc3a3',
    messagingSenderId: '816750229018',
    projectId: 'notify-b02c5',
    storageBucket: 'notify-b02c5.appspot.com',
    iosBundleId: 'com.example.week1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrJsnE_XJRHnMq3ay-aOdKartD679tCDs',
    appId: '1:816750229018:ios:f4fe470e1a9bde24ebc3a3',
    messagingSenderId: '816750229018',
    projectId: 'notify-b02c5',
    storageBucket: 'notify-b02c5.appspot.com',
    iosBundleId: 'com.example.week1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1LQcdUl6NLwwZ3G7Fi9Fl1LjSLb9rgvU',
    appId: '1:816750229018:web:9b158c8b3ad9c10eebc3a3',
    messagingSenderId: '816750229018',
    projectId: 'notify-b02c5',
    authDomain: 'notify-b02c5.firebaseapp.com',
    storageBucket: 'notify-b02c5.appspot.com',
  );
}
